reversed_icons: false

# Lemonbar's configuration
lemonbar:
  foreground: foreground
  background: background
  format: clock bandwidth|music|cpu temperature memory pulseaudio
# geometry: 1600x16+0+0
  fonts:
    - -arianon-synepis-normal-r-normal--11-80-100-100-c-60-iso10646-1
    - -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1
  clickable_areas: 10
  bottom: false
  force_docking: false

# Mkbar
mkbar:
  char1: ━
  char2: ━
  size: 16
  foreground: :foreground
  background: :darkblack

# Widgets
clock:
  icon: 
  color: :magenta
  format: "%A, %d/%m · %I:%M %p"
  reload: 60

music:
  icons: [,]
  colors: [blue, red]
  buttons:
    :1: mpc -q toggle
    :3: mpc seek 0%
    :4: mpc -q prev
    :5: mpc -q next

pulseaudio:
  bar: true
  icons: [, ]
  colors: [green, red]
  buttons:
    :1: pactl set-sink-mute 0 toggle
    :4: pactl set-sink-volume 0 +5%
    :5: pactl set-sink-volume 0 -5%

memory:
  bar: no
  icon: 
  color: :cyan
  reload: 1

cpu:
  bar: no
  icon: 
  color: :yellow
  reload: 1

bandwidth:
  # percentage:
  #   # your max bytes/s, required to calculate percentage
  #   maxes: [172000,65536]
  #   bar: true
  icons: [,]
  colors: [green, blue]
  reload: 1

temperature:
  # degrees | percentage | bar | colored_bar
  type: degrees
  icon: 
  color: :red
  reload: 1
