# Colors definitions.
colors:
  background:  &background  '#14181F'
  black:       &black       '#2B303B'
  blue:        &blue        '#8FA1B3'
  cyan:        &cyan        '#96B5B4'
  foreground:  &foreground  '#B7BDCC'
  green:       &green       '#A3BE8C'
  magenta:     &magenta     '#B48EAD'
  red:         &red         '#BF616A'
  white:       &white       '#B9BBBE'
  yellow:      &yellow      '#EBCB8B'

# Lemonbar's configuration
lemonbar:
  foreground: *foreground
  background: *background
  format: left|center|right
  fonts:
    - -lucy-tewi-medium-r-normal--11-90-75-75-m-60-iso10646-1
    - -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1
  clickable_areas: 20

# Mkbar
mkbar:
  char1: ━
  char2: ━
  size: 20
  foreground: *foreground
  background: *background

# Widgets
time:
  icon: 
  color: &blue
  format: "%H:%M:%S"
  rate: 1

music:
  icon: [,]
  color: [*blue, *red]

volume:
  bar: true
  icon: [, ]
  color: [*green, *red]

memory:
  bar: true
  icon: 
  color: *cyan
  rate: 1

cpu:
  bar: true
  icon: 
  color: *yellow
  rate: 1
