# Colors definitions.
colors:
  background:  &background  '#14181F'
  black:       &black       '#2B303B'
  blue:        &blue        '#8FA1B3'
  cyan:        &cyan        '#96B5B4'
  foreground:  &foreground  '#B7BDCC'
  green:       &green       '#A3BE8C'
  magenta:     &magenta     '#B48EAD'
  red:         &red         '#BF616A'
  white:       &white       '#B9BBBE'
  yellow:      &yellow      '#EBCB8B'

# Lemonbar's configuration
lemonbar:
  foreground: *foreground
  background: *background
  format: clock|music|cpu memory pulseaudio
  geometry: 1600x16+0+0
  fonts:
    - -lucy-tewi-medium-r-normal--11-90-75-75-m-60-iso10646-1
    - -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1
  clickable_areas: 10
  bottom: false
  force_docking: false

# Mkbar
mkbar:
  char1: ━
  char2: ━
  size: 16
  foreground: *foreground
  background: *black

# Widgets
clock:
  icon: 
  color: *magenta
  format: "%I:%M:%S %p"
  reload: 1

music:
  icons: [,]
  colors: [*blue, *red]
  buttons:
    :1: mpc -q toggle
    :4: mpc -q prev
    :5: mpc -q next

pulseaudio:
  bar: true
  icons: [, ]
  colors: [*green, *red]
  buttons:
    :1: pactl set-sink-mute 0 toggle
    :4: pactl set-sink-volume 0 +5%
    :5: pactl set-sink-volume 0 -5%

memory:
  bar: colored
  icon: 
  color: *cyan
  reload: 1

cpu:
  bar: colored
  icon: 
  color: *yellow
  reload: 1
