:lemonbar:
  # :background: '#4400000'
  # :foreground: '#FF2b303b'
  :fonts:
    - -lucy-tewi-medium-r-normal--11-90-75-75-m-60-iso10646-1
    - -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1

:mkbar:
   # :char1:   '|'
   # :char2:   '>'
   :size:    16

:colors:
  :background: 0x14181F
  :black:      0x2B303B
  :blue:       0x8FA1B3
  :cyan:       0x96B5B4
  :foreground: 0xB7BDCC
  :green:      0xA3BE8C
  :magenta:    0xB48EAD
  :red:        0xBF616A
  :white:      0xB9BBBE
  :yellow:     0xEBCB8B

:icons:
  :clock:   
  :cpu:     
  :memory:  
  :netup:   
  :netdown: 
  :music:   
  :paused:  
  :volume:  
  :muted:   